matrix:
  include:
    - stage: "WebPack, Build and Test"
      os: osx
      env:
        - WebPack="iOS"
      osx_image: xcode10.1
      language: node_js
      node_js: "10"
      jdk: oraclejdk8
      language: ruby
      rvm:
        - 2.3.7
      script: cd src && npm i && cd ../demo && npm i && tns build ios --bundle --env.uglify && cd ../demo-angular && npm i && tns build ios --bundle --env.uglify --env.aot
    - language: android
      os: linux
      env:
        - WebPack="Android"
      jdk: oraclejdk8
      before_install: nvm install 10.15.0
      script: cd src && npm i && cd ../demo && npm i && tns build android --bundle --env.uglify --env.snapshot && cd ../demo-angular && tns build android --bundle --env.uglify --env.snapshot --env.aot
    - language: android
      env:
        - BuildAndroid="26"
      os: linux
      jdk: oraclejdk8
      before_install: nvm install stable
      script:
        - cd src && npm i && cd ../demo && tns build android && cd ../demo-angular && tns build android
    - os: osx
      env:
        - BuildiOS="12"
        - Xcode="10.1"
      osx_image: xcode10.1
      language: node_js
      node_js: "10"
      jdk: oraclejdk8
      language: ruby
      rvm:
        - 2.3.7
      script:
        - cd src && npm i && cd ../demo && tns build ios && cd ../demo-angular && tns build ios

android:
  components:
    - tools
    - platform-tools
    - build-tools-28.0.3
    - android-28
    - android-26
    - android-23
    - extra-android-m2repository

install:
    - echo no | npm install -g nativescript
    - tns usage-reporting disable
    - tns error-reporting disable
    - tns doctor
