matrix:
  include:
    - stage: "WebPack, Build and Test"
      os: osx
      env:
        - WebPack="iOS"
      osx_image: xcode9.2
      language: node_js
      node_js: "6"
      jdk: oraclejdk8
      script: cd src && npm i && cd ../demo && npm i && tns build ios --bundle --env.uglify && cd ../demo-angular && npm i && tns build ios --bundle --env.uglify
    - language: android
      os: linux
      env:
        - WebPack="Android"
      jdk: oraclejdk8
      before_install: nvm install 6.10.3
      script: cd src && npm i && cd ../demo && npm i && tns build android --bundle --env.uglify --env.snapshot && cd ../demo-angular && tns build android --bundle --env.uglify --env.snapshot
    - language: android
      env:
        - BuildAndroid="26"
      os: linux
      jdk: oraclejdk8
      before_install: nvm install stable
      script:
        - cd src && npm i && cd ../demo && tns build android && cd ../demo-angular && tns build android
    - os: osx
      env:
        - BuildiOS="11"
        - Xcode="9.2"
      osx_image: xcode9.2
      language: node_js
      node_js: "6"
      jdk: oraclejdk8
      script:
        - cd src && npm i && cd ../demo && tns build ios && cd ../demo-angular && tns build ios

android:
  components:
    - tools
    - platform-tools
    - build-tools-26.0.2
    - android-26
    - android-23
    - extra-android-m2repository
    - sys-img-armeabi-v7a-android-21

install:
    - echo no | npm install -g nativescript
    - tns usage-reporting disable
    - tns error-reporting disable