matrix:
  include:
    - stage: "WebPack, Build and Test"
      os: osx
      env:
        - WebPack="iOS"
      osx_image: xcode10.0
      language: node_js
      node_js: "8"
      jdk: oraclejdk8
      script: cd src && npm i && cd ../demo && npm i && tns build ios --bundle --env.uglify && cd ../demo-angular && npm i && tns build ios --bundle --env.uglify --env.aot
    - language: android
      os: linux
      env:
        - WebPack="Android"
      jdk: oraclejdk8
      before_install: nvm install 8
      script: cd src && npm i && cd ../demo && npm i && tns build android --bundle --env.uglify --env.snapshot && cd ../demo-angular && tns build android --bundle --env.uglify --env.snapshot --env.aot
    - language: android
      env:
        - BuildAndroid="28"
      os: linux
      jdk: oraclejdk8
      before_install: nvm install stable
      script:
        - cd src && npm i && cd ../demo && tns build android && cd ../demo-angular && tns build android
    - os: osx
      env:
        - BuildiOS="12"
        - Xcode="10.0"
      osx_image: xcode10.0
      language: node_js
      node_js: "8"
      jdk: oraclejdk8
      script:
        - cd src && npm i && cd ../demo && tns build ios && cd ../demo-angular && tns build ios

android:
  components:
    - tools
    - platform-tools
    - build-tools-28.0.3
    - android-28
    - extra-android-m2repository
    - sys-img-armeabi-v7a-android-21

before_install:
    - sudo pip install --upgrade pip
    - sudo pip install six

install:
    - echo no | npm install -g nativescript
    - tns usage-reporting disable
    - tns error-reporting disable